name: the_citizens
version: 0.1.1
description: >
  “LocalDB: Portal” - A Web Site of Database Portal on/for the Local Citizens.
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://localdb.dev-pack.org/portal
repository: https://github.com/the-citizens/the_citizens
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  jaspr: ^0.20.0
  supabase: ^2.9.0
  http: ^1.5.0
  yaml: ^3.1.3
  color: ^3.0.0
  sitemap: ^1.0.0
topics:
  - localmin
  - website
publish_to: none
