name: the_citizens
version: 0.1.1
description: >
  “LocalDB: Portal” - A Web Site of Database Portal on/for the Local Citizens.
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://localdb.dev-pack.org/portal
repository: https://github.com/the-citizens/the_citizens
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  jaspr: ^0.20.0
  supabase: ^2.9.0
  http: ^1.5.0
  pointycastle: ^4.0.0
  archive: ^3.6.1
  es_compression: ^2.0.14
  yaml: ^3.1.3
  ini: ^2.1.0
  csv: ^6.0.0
  excel: ^4.0.6
  color: ^3.0.0
  sitemap: ^1.0.0
  symbol_sdk: ^1.1.0
executables:
  loctk:
  locktk:
topics:
  - localmin
  - portal
  - twitter
publish_to: none
